#!/bin/sh

cd ..

# Install Doxygen 1.9.4
# This is because this version is compatible of my header template.
curl -kLSs https://github.com/doxygen/doxygen/releases/download/Release_1_9_4/doxygen-1.9.4.linux.bin.tar.gz -o doxygen-1.9.4.linux.tar.gz
gunzip doxygen-1.9.4.linux.tar.gz    # uncompress the archive
tar xf doxygen-1.9.4.linux.tar       # unpack it
cd doxygen-1.9.4
sudo make install
cd ..

# Run Doxygen
cd dg-cpp && doxygen ./docs/Doxyfile
